// <auto-generated />
namespace BasvuruPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _12012022_hatausulyolsuzluktableadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12012022_hatausulyolsuzluktableadd));
        
        string IMigrationMetadata.Id
        {
            get { return "202201120019127_12012022_hatausulyolsuzluktableadd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
