// <auto-generated />
namespace BasvuruPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _07022022KaysemBasvuru : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_07022022KaysemBasvuru));
        
        string IMigrationMetadata.Id
        {
            get { return "202202071424144__07022022KaysemBasvuru"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
