// <auto-generated />
namespace BasvuruPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _03022022KursBasvuruEdit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03022022KursBasvuruEdit));
        
        string IMigrationMetadata.Id
        {
            get { return "202202030716559_03022022KursBasvuruEdit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
