// <auto-generated />
namespace BasvuruPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class araconay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(araconay));
        
        string IMigrationMetadata.Id
        {
            get { return "202110061103233_araconay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
