//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasvuruPortal.ObisisVeritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBP_KULLANICI
    {
        public int KULLANICI_KODU { get; set; }
        public string EMAIL { get; set; }
        public string SIFRE { get; set; }
        public Nullable<bool> AKTIF { get; set; }
        public Nullable<byte> YETKI { get; set; }
        public Nullable<System.Guid> AKTIVASYON_KODU { get; set; }
        public Nullable<int> BASVURU_TURU_KODU { get; set; }
        public Nullable<System.DateTime> KAYIT_TARIHI { get; set; }
        public string KULLANICI_ADI_SOYADI { get; set; }
        public string MEKTUP_EMAIL { get; set; }
    }
}
